services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
    environment:
      - DOCKER_DB=true
      - MONGO_URI=mongodb://mongo:27017/fantastic_game
    expose:
      - "5000"
    volumes:
      - ./backend/public/avatars:/app/public/avatars   # ← mount for persistence
      - ./logs:/logs

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017:27017"

  nginx:
    build: ./frontend   # <<<<<< NGINX builds from frontend now
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/zzz_override.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-data:



# version: "3.8"

# services:
#   frontend:
#     build:
#       context: ./frontend
#     container_name: frontend
#     restart: always
#     ports:
#       - "8080:80"

#   backend:
#     build:
#       context: ./backend
#     container_name: backend
#     restart: always
#     depends_on:
#       - mongo
#     environment:
#       - DOCKER_DB=true
#       - MONGO_URI=mongodb://mongo:27017/fantastic_game
#     expose:
#       - "5000"
#     volumes:
#       - ./logs:/logs

#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     restart: always
#     volumes:
#       - mongo-data:/data/db

#   # nginx:
#   #   image: nginx:latest
#   #   container_name: nginx
#   #   ports:
#   #     - "8080:80"
#   #     - "443:443"
#   #   volumes:
#   #     - ./frontend/dist:/usr/share/nginx/html:ro
#   #     - ./nginx/zzz_override.conf:/etc/nginx/conf.d/default.conf

# volumes:
#   mongo-data: