services:
  mongodb:
    image: mongo:4.2.5
    container_name: mongodb
    ports:
#      have to change this to something else for security
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

#  backend:
#    build: ./server
#    container_name: flask-backend
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./server:/app
#    depends_on:
#      - mongodb
#    environment:
##      hardcoded localhost!!!!
#      - MONGO_URI=mongodb://admin:password@mongodb:27017/
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: